2020-12-22 10:21:04,589 ERROR: Exception on /login [GET] [in /home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/radek/PycharmProjects/microblog/app/routes.py", line 67, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/radek/PycharmProjects/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/radek/PycharmProjects/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/radek/PycharmProjects/microblog/app/templates/login.html", line 26, in block "content"
    <a href="{{ url_for('reset_password_request' )}}">Click to Reset It</a>
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_passowrd_request' instead?
2020-12-22 10:21:08,092 ERROR: Exception on /login [GET] [in /home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/radek/PycharmProjects/microblog/app/routes.py", line 67, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/radek/PycharmProjects/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/radek/PycharmProjects/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/radek/PycharmProjects/microblog/app/templates/login.html", line 26, in block "content"
    <a href="{{ url_for('reset_password_request' )}}">Click to Reset It</a>
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/radek/PycharmProjects/microblog/flask_venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_passowrd_request' instead?
2020-12-22 10:22:07,712 INFO: Microblog startup [in /home/radek/PycharmProjects/microblog/app/__init__.py:53]
